name: 'Codesign'
description: ''
inputs:
  path:
    description: Path to the executable or binary to be codesigned
    required: true
  isInstaller:
    description: Whether the signed binary is an installer or not
    default: false
outputs:
  signed-path:
    description: 'The resulting signed binary'
runs:
  using: 'node12'
  main: 'index.js'
