name: 'Get version'
description: ''
inputs:
  csharp:
    description: Get the version from Nerdbank.GitVersioning environment variables.
  cargo:
    description: Get the version from the Cargo.toml file at the given path, or base if value is 'true'
  speller-manifest:
    description: Speller manifest
  plist:
    description: ... plist
  xcode:
    description: derive from xcodebuild
  nightly-channel:
    description: The nightly channel to use
  insta-stable:
    description: When `true` don't release to the `beta` channel but to stable immediately
outputs:
  version:
    description: The generated version
  channel:
    description: Pahkat channel to deploy to
runs:
  using: 'node12'
  main: 'index.js'
