name: "Deploy spellers"
description: ""
inputs:
  speller-type:
    description: "The speller type from the matrix"
    required: true
  speller-manifest-path:
    description: "Path to the speller manifest"
    required: true
    default: "manifest.toml"
  payload-path:
    description: Path to the payload to be uploaded
    required: true
  version:
    description: Version
    required: true
  repo:
    description: Pahkat repository to upload payload and metadata to
    required: true
    # Temporary workaround until upload service moved to Divvun
    default: "https://pahkat.thetc.se/main/"
  channel:
    description: Pahkat repository channel
    required: false
runs:
  using: "node12"
  main: "index.js"
