name: "Deploy a thing"
description: ""
inputs:
  package-id:
    description: Package identifier (the part that comes after /packages/ in the package key URL)
    required: true
  platform:
    description: "Platform"
    required: true
  version:
    description: "Version"
    required: true
  payload-path:
    description: "Path to payload artifact to deploy"
    required: true
  repo:
    description: "Pahkat repository to deploy to"
    required: true
  channel:
    description: "Pahkat channel"
    required: false
  macos-pkg-id:
    description: "macOS operating system package identifier (macOS: required)"
    required: false
  macos-requires-reboot:
    description: ""
    required: false
  macos-targets:
    description: ""
    required: false
  windows-product-code:
    description: "Windows product code (Windows: required)"
    required: false
  windows-kind:
    description: The kind of installer
    required: false
  windows-requires-reboot:
    description: ""
    required: false
  GITHUB_TOKEN:
    description: Github token
    required: true
runs:
  using: "node12"
  main: "index.js"
