name: "Bundle spellers"
description: ""
inputs:
  speller-type:
    description: "The speller type from the matrix"
    required: true
  speller-manifest-path:
    description: "Path to the speller manifest"
    required: true
    default: "manifest.toml"
  speller-paths:
    description: A JSON object consisting of desktop and mobile keys with paths to each zhfst speller
    required: true
  version:
    description: Bundle version
    required: true
  GITHUB_TOKEN:
    description: Github token
    required: true
outputs:
  payload-path:
    description: "The bundled speller ready to be signed and uploaded to a Pahkat repository"
runs:
  using: "node12"
  main: "index.js"
